# Generated by Django 5.2.4 on 2025-07-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='file_name',
            new_name='file_path',
        ),
    ]
